Add common error handling to wrapper script. (#152)
* Remove trailing whitespace.

* Return early if failures.

* Always run customer supplied start command.

* Consolidate common setup code.

* Pull out base path to make it easier to test.

* Include original NODE_OPTIONS if they exist.

* Use a common directory for binaries.

* Update log message.

* Update paths to new locations.

* On SIGINT also kill the trace-agent.

* Move variables to global and allow overrides.

* Install to specific directory and fallback NODE_OPTIONS.

* Log binaries url.

* Download dotnet tracer.

* Use curl instead of wget.

diff --git a/node/linux/datadog-aas-node-linux/datadog_wrapper b/node/linux/datadog-aas-node-linux/datadog_wrapper
--- a/node/linux/datadog-aas-node-linux/datadog_wrapper
+++ b/node/linux/datadog-aas-node-linux/datadog_wrapper
@@ -1,44 +1,76 @@
-#!/usr/bin/env sh 
+#!/usr/bin/env sh
+
+CURRENT_DIR=$(pwd)
+
+if [ -z "$DD_DIR" ]; then
+    DD_DIR="/home/datadog"
+fi
+
+if [ -z "$DD_BINARIES_URL" ]; then
+    DD_BINARIES_URL="https://gist.github.com/jcstorms1/7e73ab0da121f42d1843dac5b75c21cb/raw"
+fi
+
+setUpCommonEnv() {
+    echo "Creating datadog directory"
+    mkdir -p $DD_DIR && cd $DD_DIR || return
+
+    echo "Downloading required datadog binaries from $DD_BINARIES_URL"
+    curl -L $DD_BINARIES_URL/datadog.tar.gz -o datadog.tar.gz || return
+
+    echo "Decompressing files"
+    tar -xzf datadog.tar.gz || return
+    rm datadog.tar.gz
+
+    echo "Starting trace agent"
+    ./trace-agent &
+    TRACER_PID=$!
+    trap 'kill $TRACER_PID ; exit' INT
+}
 
 setUpNodeEnv() {
     echo "Setting up Datadog tracing for Node"
-    DD_DIR="/home/site/wwwroot/datadog-js"
-    mkdir -p $DD_DIR
 
-    curl -L "https://gist.github.com/jcstorms1/7e73ab0da121f42d1843dac5b75c21cb/raw/datadog-js.tar.gz" -o $DD_DIR/datadog-js.tar.gz
-    tar -xzf $DD_DIR/datadog-js.tar.gz && rm $DD_DIR/datadog-js.tar.gz
-    
-    export NODE_OPTIONS="--require=$DD_DIR/node_modules/dd-trace/init --require=$DD_DIR/start-trace-agent.js"
+    setUpCommonEnv || return
+
+    echo "Installing Node tracer"
+    npm install --prefix $DD_DIR dd-trace || return
+
+    ORIG_NODE_OPTIONS=$NODE_OPTIONS
+    export NODE_OPTIONS="--require=$DD_DIR/node_modules/dd-trace/init $ORIG_NODE_OPTIONS"
+
+    # confirm updates to NODE_OPTIONS
+    node --help >/dev/null || (export NODE_OPTIONS=$ORIG_NODE_OPTIONS && return)
 }
 
 setUpDotnetEnv() {
     echo "Setting up Datadog tracing for .NET"
 
-    echo "Downloading "
-    curl -L "https://gist.github.com/jcstorms1/a712f0df568e81b055b2234b4ec71cd9/raw/datadog-dotnet.tar.gz" -o /home/datadog-dotnet.tar.gz
-    
-    cd /home/
-    tar -xzf datadog-dotnet.tar.gz && rm datadog-dotnet.tar.gz
+    setUpCommonEnv || return
 
-    echo "Starting application"
+    if [ -z "$DD_DOTNET_TRACER_VERSION" ]; then
+        DD_DOTNET_TRACER_VERSION=2.19.0
+    fi
+    DD_DOTNET_TRACER_FILE=datadog-dotnet-apm-${DD_DOTNET_TRACER_VERSION}.tar.gz
+    DD_DOTNET_TRACER_URL=https://github.com/DataDog/dd-trace-dotnet/releases/download/v${DD_DOTNET_TRACER_VERSION}/${DD_DOTNET_TRACER_FILE}
+
+    echo "Installing .NET tracer from $DD_DOTNET_TRACER_URL"
+    curl -L $DD_DOTNET_TRACER_URL -o $DD_DOTNET_TRACER_FILE|| return
+    tar -xzf $DD_DOTNET_TRACER_FILE || return
+
     export CORECLR_ENABLE_PROFILING=1
     export CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
-    export CORECLR_PROFILER_PATH=/home/datadog-dotnet/datadog/Datadog.Trace.ClrProfiler.Native.so
-    export DD_DOTNET_TRACER_HOME=/home/datadog-dotnet/datadog
-
-    ./datadog-dotnet/trace-agent &
-    
-    cd /home/site/wwwroot
-    $DD_START_APP
+    export CORECLR_PROFILER_PATH=${DD_DIR}/Datadog.Trace.ClrProfiler.Native.so
+    export DD_DOTNET_TRACER_HOME=${DD_DIR}
 }
 
 if [ -z "$DD_RUNTIME" ]; then
     echo "Runtime is not set. Skipping Datadog startup"
-    $DD_START_APP
-    exit
 elif [ "$DD_RUNTIME" = "node" ]; then
     setUpNodeEnv;
-    $DD_START_APP
 elif [ "$DD_RUNTIME" = "dotnet" ]; then
     setUpDotnetEnv;
 fi
+
+echo "Executing start command: \"$DD_START_APP\""
+cd $CURRENT_DIR
+eval "$DD_START_APP"
