[Serverless]  Add logic to catch curl failures in the Linux script (#162)
* add logic to catch curl failures

* typos

* make message more detailed

* add return statement

diff --git a/linux/datadog_wrapper b/linux/datadog_wrapper
--- a/linux/datadog_wrapper
+++ b/linux/datadog_wrapper
@@ -14,11 +14,11 @@ if [ -z "$DD_BINARIES_URL" ]; then
 fi
 
 if [ -z "$DD_AAS_LINUX_VERSION" ]; then
-    DD_AAS_LINUX_VERSION="linux-v0.1.2-beta"
+    DD_AAS_LINUX_VERSION="linux-v0.1.3-beta"
 fi
 
 setUpCommonEnv() {
-    echo "Creating datadog directory"
+    echo "Creating Datadog directory"
     mkdir -p $DD_DIR && cd $DD_DIR || return
 
     FILE=trace-agent-${DD_AAS_LINUX_VERSION}.tar.gz
@@ -30,11 +30,15 @@ setUpCommonEnv() {
             rm trace-agent* 
         fi
 
-        echo "Downloading required datadog binaries from $DD_BINARIES_URL"
-        curl -L $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE -o $FILE || return
-
-        echo "Decompressing files"
-        tar -zxf $FILE || return
+        echo "Downloading required Datadog binaries from $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE"
+        if curl -L --fail $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE -o $FILE; then echo
+            echo "Decompressing files"
+            tar -zxf $FILE || return
+        else 
+            echo "Failed to download the Datadog binary succesfully."
+            return
+        fi
+        
     else
         echo "Version $DD_AAS_LINUX_VERSION of the trace agent previously installed"
     fi
