[Serverless] Add versioning and update readme for Linux (#159)
* add versioning and update readme

* add return to yarn command

* clean up & comments

* typo

* whitespace

diff --git a/linux/datadog_wrapper b/linux/datadog_wrapper
--- a/linux/datadog_wrapper
+++ b/linux/datadog_wrapper
@@ -10,19 +10,35 @@ if [ -z "$DD_DIR" ]; then
 fi
 
 if [ -z "$DD_BINARIES_URL" ]; then
-    DD_BINARIES_URL="https://github.com/DataDog/datadog-aas-extension/releases/download/linux-v0.1.1-beta"
+    DD_BINARIES_URL="https://github.com/DataDog/datadog-aas-extension/releases/download"
+fi
+
+if [ -z "$DD_AAS_LINUX_VERSION" ]; then
+    DD_AAS_LINUX_VERSION="linux-v0.1.2-beta"
 fi
 
 setUpCommonEnv() {
     echo "Creating datadog directory"
     mkdir -p $DD_DIR && cd $DD_DIR || return
 
-    echo "Downloading required datadog binaries from $DD_BINARIES_URL"
-    curl -L $DD_BINARIES_URL/trace-agent.gz -o trace-agent.gz || return
+    FILE=trace-agent-${DD_AAS_LINUX_VERSION}.tar.gz
 
-    echo "Decompressing files"
-    gzip -d trace-agent.gz || return
+    if [ ! -f $FILE ]; then 
 
+        if [ -f "trace-agent" ]; then 
+            echo "Removing old versions of the trace agent"
+            rm trace-agent* 
+        fi
+
+        echo "Downloading required datadog binaries from $DD_BINARIES_URL"
+        curl -L $DD_BINARIES_URL/$FILE -o $FILE || return
+
+        echo "Decompressing files"
+        tar -zxf $FILE || return
+    else
+        echo "Version $DD_AAS_LINUX_VERSION of the trace agent previously installed"
+    fi
+    
     echo "Starting trace agent"
     ./trace-agent &
     TRACER_PID=$!
@@ -35,7 +51,7 @@ setUpNodeEnv() {
     setUpCommonEnv || return
 
     echo "Installing Node tracer"
-    npm install --prefix $DD_DIR dd-trace || return
+    yarn add dd-trace || return
 
     ORIG_NODE_OPTIONS=$NODE_OPTIONS
     export NODE_OPTIONS="--require=$DD_DIR/node_modules/dd-trace/init $ORIG_NODE_OPTIONS"
